{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $name, $config := .Values.configmap.values }}
  {{ $name }}: {{ $config | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.nexus.externalConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-nexus-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.nexus.config | nindent 4 }}
{{- end }}
---
